# Generated by Django 5.1.1 on 2024-09-22 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersChara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.IntegerField(blank=True, null=True)),
                ('charanum', models.ForeignKey(blank=True, db_column='charanum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='entities.charainfo')),
                ('usernum', models.ForeignKey(blank=True, db_column='usernum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsersChara',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendnum', models.ForeignKey(blank=True, db_column='friendnum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='usersfriends_friendnum_set', to=settings.AUTH_USER_MODEL)),
                ('usernum', models.ForeignKey(blank=True, db_column='usernum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsersFriends',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(blank=True, null=True)),
                ('jewel', models.IntegerField(blank=True, null=True)),
                ('usernum', models.ForeignKey(blank=True, db_column='usernum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsersItem',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('usernum', models.ForeignKey(blank=True, db_column='usernum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsersOption',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('lessonmapnum', models.ForeignKey(blank=True, db_column='lessonmapnum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lessons.lessonmap')),
                ('usernum', models.ForeignKey(blank=True, db_column='usernum', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UsersProgress',
                'managed': True,
            },
        ),
    ]
