# Generated by Django 5.1.1 on 2024-09-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userschara',
            name='charanum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userschara',
            name='lvl',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userschara',
            name='usernum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersfriends',
            name='friendnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersfriends',
            name='usernum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersitem',
            name='jewel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersitem',
            name='money',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersitem',
            name='usernum',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersoption',
            name='birthday',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='usersoption',
            name='language',
            field=models.TextField(default='Korean'),
        ),
        migrations.AlterField(
            model_name='usersoption',
            name='usernum',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersprogress',
            name='lessonmapnum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersprogress',
            name='progress',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='usersprogress',
            name='usernum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userschara',
            unique_together={('usernum', 'charanum')},
        ),
        migrations.AlterUniqueTogether(
            name='usersfriends',
            unique_together={('usernum', 'friendnum')},
        ),
        migrations.AlterUniqueTogether(
            name='usersprogress',
            unique_together={('usernum', 'lessonmapnum')},
        ),
    ]
