# Generated by Django 5.1.1 on 2024-09-22 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lessonnum', models.IntegerField(primary_key=True, serialize=False)),
                ('theme', models.TextField(blank=True, null=True)),
                ('x_cor', models.FloatField(blank=True, null=True)),
                ('y_cor', models.FloatField(blank=True, null=True)),
                ('btnimg', models.TextField(blank=True, null=True)),
                ('bgimg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonMap',
            fields=[
                ('lessonmapnum', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('bgimg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'LessonMap',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chinese',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.lesson')),
            ],
            options={
                'db_table': 'Chinese',
                'managed': True,
            },
            bases=('lessons.lesson',),
        ),
        migrations.CreateModel(
            name='English',
            fields=[
                ('lesson_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lessons.lesson')),
            ],
            options={
                'db_table': 'English',
                'managed': True,
            },
            bases=('lessons.lesson',),
        ),
    ]
